### ISSUE TITLE
vst3sdk out-of-date

### ISSUE THREAD

**Issue by dvzrv** [sfztools/sfizz-ui#126]
Hi! :wave: 

When getting around to create this package for Arch Linux finally I ran into issues with the bundled vst3sdk being too out-of-date:

```
CMake Error at plugins/editor/cmake/Vstgui.cmake:122 (target_sources):
  Cannot find source file:

    /usr/src/vst3sdk/vstgui4/vstgui/lib/platform/linux/cairocontext.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  plugins/editor/CMakeLists.txt:9 (include)
```

We are currently on 3.7.9_build_61 and will update to 3.7.10_build_14. Would it be possible to bump the version used in this repository as well? :)

**Comment by redtide** [comment]
hello, I tried once to understand what kind of change they made but at some point I gave up.
I'll retry in the next days.

**Comment by redtide** [comment]
the error you faced were from VSTGUI, that is now updated to the current 4.13.3, I'll see what we can do with the SDK.
