### ISSUE TITLE
Linux .clap plugin format support

### ISSUE THREAD

**Issue by ghost** [sfztools/sfizz-ui#141]
Hi,

I would like to know if there is the possibility i have sfizz (sfizz-ui) in clap format, 
thanks

**Comment by RustoMCSpit** [comment]
currently not

**Comment by RustoMCSpit** [comment]
https://github.com/sfztools/sfizz-ui/discussions/109

**Comment by ghost** [comment]
> currently not

OK, thanks anyway for the answer! I hope that in the future maybe.....

cheers
