### ISSUE TITLE
FL Studio 20.8.4 can't load sfizz 1.2.0 as VSTi, only as VST (effect)

### ISSUE THREAD

**Issue by michael02022** [sfztools/sfizz-ui#3]
Hi, I have this issue which not sure how to solve it, i can't use sfizz as an instrument (runs fine as an effect) (Edit: the old versions works fine as VSTi)
![image](https://user-images.githubusercontent.com/86170350/228924402-3a26646f-e95b-4279-9dd2-ba53fc334172.png)

**Comment by Matojeje** [comment]
You can still use it by assigning it a MIDI input channel in the VST wrapper settings, similar to Fruity LSD:
![obrazek](https://github.com/sfztools/sfizz-ui/assets/3956863/0204093b-043c-4979-a18c-b2d14e130ecf)

**Comment by michael02022** [comment]
I found how to fix it. Basically, it's a FL Studio problem. I've read you have to use verify plugins to detect that it's an instrument due to some code thing in the VST3 format. At the end it didn't solve anything in this way. But if I go to Plugin Database -> Generators -> VST3, I can find sfizz and sfizz-multi, drag and drop it and now it works as a instrument plugin.
![image](https://github.com/sfztools/sfizz-ui/assets/86170350/940cee9f-e464-4f1f-90c2-d43c6c07325b)

**Comment by michael02022** [comment]
Just to add an important detail. If you never installed sfizz before, make sure to enable "verify plugins" when you scan plugins in FL Studio. In this way it will let you open sfizz from FL Browser as mentioned before.

**Comment by redtide** [comment]
> Just to add an important detail. If you never installed sfizz before, make sure to enable "verify plugins" when you scan plugins in FL Studio. In this way it will let you open sfizz from FL Browser as mentioned before.

IDK FL Studio, but if this is not something done regularly then we need to add this on our documentation

**Comment by michael02022** [comment]
> > Just to add an important detail. If you never installed sfizz before, make sure to enable "verify plugins" when you scan plugins in FL Studio. In this way it will let you open sfizz from FL Browser as mentioned before.
> 
> IDK FL Studio, but if this is not something done regularly then we need to add this on our documentation

Absolutely for any FL Studio user, because this is not easy to figure out.
