### ISSUE TITLE
Sfizz LV2 and VST crash Ardour 6.5.x and Reaper 6.19 on Linux

### ISSUE THREAD

**Issue by ghost** [sfztools/sfizz-ui#68]
Sfizz build (inclusive of commit cbcc875) allows for loading of scala file and tuning preset but after several seconds of playing (maybe sometimes just shy of a minute), Sfizz crashes Ardour and Reaper (native)

**Comment by ghost** [comment]
Through process of elimination, I believe the root cause of the crash is when the polyphony setting (under engine) is moved away from the value of 64.

**Comment by jpcima** [comment]
It's most likely fixed in the latest, please confirm

**Comment by ghost** [comment]
After a brief play, I do believe the polyphony issue is fixed. Thanks!
