### ISSUE TITLE
Partial support of Aria bank XML support

### ISSUE THREAD

**Issue by a13** [sfztools/sfizz-ui#8]
Hi. I tried to get Plogue sforzatron working using out-of-the-box SFZ files. 

It didn't work as is, but my investigation led me to the issue

SFZ files use values like 
```
default_path=$sample_dir/Cello/
```
where `$sample_dir` is defined inside the Plogue.sforzatron.bank.xml file

```
<Define name="$sample_dir" value="../Samples"/>
```

So when I replaced it with the value from the xml - everything worked just fine. I understand that to support the whole Aria stuff is impossible (given it's closed-source) and out of the project's scope - is it possible to add some rudimental `<Define>` parser?

**Comment by redtide** [comment]
It shouldn't be hard to implement and not that much out of scope if we support ARIA opcodes; why not an XML extension. I wonder how many instruments use this behavior.
