### ISSUE TITLE
Missing dependencies on .deb in ubuntu repository

### ISSUE THREAD

**Issue by TriYop** [sfztools/sfizz-ui#93]
I recently installed sfizz from the ubuntu repository on an ubuntu studio (23.04) freshly installed.
When I try to launch sfizz UI from ardour/mixbus, I had the following error displayed in the terminal and the UI not showing.

`suil error: Unable to open UI library /usr/lib/lv2/sfizz.lv2/Contents/Binary/sfizz_ui.so (/usr/lib/lv2/sfizz.lv2/Contents/Binary/sfizz_ui.so: undefined symbol: pango_font_metrics_get_height)`

after a little googling, it seemed that this dependency was provided by `libpango-perl` which I installed and solved the issue.

May you please add the dependency to the package in order it is automatically installed by apt ?

**Comment by redtide** [comment]
Hi! Could you please provide a link to the package you downloaded and installed?

**Comment by TriYop** [comment]
Here is the package description page
https://packages.ubuntu.com/lunar/libpango-perl
and the package link in ubuntu repository
https://packages.ubuntu.com/lunar/amd64/libpango-perl/download

**Comment by redtide** [comment]
sorry, I mean the sfizz package, I need to understand if it's one of those we provide.

**Comment by TriYop** [comment]
I guess it is
https://download.opensuse.org/repositories/home:/sfztools:/sfizz:/develop/xUbuntu_23.04/amd64/sfizz_1685544985.917d4f5-0_amd64.deb
but I followed the doc to add this repo to my apt list
https://software.opensuse.org/download.html?project=home%3Asfztools%3Asfizz%3Adevelop&package=sfizz

**Comment by redtide** [comment]
that function is part of the pango library, which we include already ([libpango1.0-dev](https://packages.ubuntu.com/lunar/libpango1.0-dev), defined in `pango/pango-font.h`). I'll need some time to discuss with Paul about this.

**Comment by paulfd** [comment]
Hi! How did you install Ardour?

**Comment by TriYop** [comment]
Ardour is part of the base packages installed in ubuntu studio, so I use this package in ubuntu/lunar repository.
ardour/lunar,now 1:7.3.0+ds0-1 amd64  [installé, automatique]

The issue was the same with Mixbus (Harrison consoles) that has been installed through a tarball package in my /opt.

In carla, the UI was not showing up until I installed the [libpango-perl]  package (which is not a requirement of [libpango1.0-dev](https://packages.ubuntu.com/lunar/libpango1.0-dev)  (I can't figure why as there seem to be no perl requirement with sfizz and pango dependencies seem to include what I expect)

**Comment by redtide** [comment]
Anyway.. I added that dependency only for the Ubuntu 23.04 package, let's see what happens, it would be nice to understand where is the culprit. Let us know if it is working now.

**Comment by redtide** [comment]
Closing, reopen if still an issue.
