### ISSUE TITLE
Unable to send project from Windows user to Linux user

### ISSUE THREAD

**Issue by vbgfhfngfdtyreyt** [sfztools/sfizz-ui#95]
I seem to be running into an issue trying to send a project from a Windows user to a Linux user. The "User SFZ folder" is set correctly on both systems, and I can send projects from Linux to Windows with no issues whatsoever. However, when trying to send a project from Windows to Linux, the Linux user gets the full Windows style path of the soundfont in the soundfont selection region:
![01](https://github.com/sfztools/sfizz-ui/assets/42302369/8914a131-caf5-4ca9-84d3-621211a5c993)

Whereas I would expect simply the name of the file to show up like so (this is what happens when I send a project from Linux to Windows and it works perfectly!)
![02](https://github.com/sfztools/sfizz-ui/assets/42302369/8885823d-fdc7-4f70-a010-289a11f331ac)

Generally speaking I would expect users from all operating systems to be able to share projects without issue (as long as the "User SFZ folder" is set correctly of course!)
sfizz 1.2.1, DAW is reaper.

Linux version is Debian 12, Windows version is Windows 7 (apologies, that is what the user is using unfortunately).

If there are test builds for a bugfix, I am happy to test on my Linux system + Windows 7 vm.

**Comment by vbgfhfngfdtyreyt** [comment]
Just tested on Windows 10 and had the same issue

**Comment by redtide** [comment]
> Just tested on Windows 10 and had the same issue

I think it's how implementation was made in general, not a "simple bug". I'll need some time to fix it though.

**Comment by atsushieno** [comment]
It is almost safe to transform the Windows file paths just by replacing '\' (backslash) as '/' (slash), if the file paths are relative i.e. the path root (e.g. `c:\`, `\\some-server`) is involved.

On various Linux filesystems, '\' is a valid filename character and thus it cannot be used as a directory separator. It is not vice versa on Windows (you cannot use '/' for a filename).

**Comment by atsushieno** [comment]
Just for record, it is actually a bug, rather than an enhancement, at least in LV2 context. [LV2 state specification](https://lv2plug.in/ns/ext/state) says:

> Plugins MUST use the type [atom:Path](https://lv2plug.in/ns/ext/atom.html#Path) for all paths in their state.

and from [LV2 Atom specification](https://lv2plug.in/ns/ext/atom.html#Path):

> A Path is a URI reference with only a path component: no scheme, authority, query, or fragment. In particular, paths to files in the same bundle may be cleanly written in Turtle files as a relative URI.

**Comment by redtide** [comment]
who said it is not?

**Comment by atsushieno** [comment]
? I did not say anyone said it is by design.

**Comment by redtide** [comment]
@vbgfhfngfdtyreyt could you please test #101? Eventually there is also #100 as alternative.
